CREATE PROC FI_SP_ConsBeneficiarioV1  
 @ID BIGINT  
AS  
BEGIN  
 IF(ISNULL(@ID,0) = 0)  
  SELECT NOME, ID, CPF, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK)  
 ELSE  
  SELECT NOME, ID, CPF, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @ID  
END
