CREATE PROC FI_SP_VerificaCliente
    @CPF VARCHAR(14),
    @ID BIGINT      = 0 
AS
BEGIN
    SELECT 1 FROM CLIENTES WHERE CPF = @CPF AND ID <> ISNULL(@ID,0)
    UNION ALL
    SELECT 1
      FROM BENEFICIARIOS
     WHERE CPF = @CPF;
END
